version: '3'
services:
  my-mongo:
    image: mongo
    ports:
      - "27017:27017"

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - PORT=8888
      - HOST=0.0.0.0
      - MONGO_CONNECTION_STRING=mongodb://my-mongo:27017/myMernApp
    restart: always
    depends_on:
      - my-mongo
    
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    restart: always
    depends_on:
      - backend
