name: CD workflow

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Update_code:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    
    - name: update by ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
        script: | 
          cd k8s-docker

          
          
