name: CD workflow

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Update_code:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    
    - name: CD
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: 22
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd k8s-docker
          git pull origin master



