name: CD workflow

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Update_Dockerfile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REPO_KEY }}

    - name: Build and push Docker image for frontend
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        tags: ghcr.io/hsienbro/frontend:latest

    - name: Build and push Docker image for backend
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: ghcr.io/hsienbro/backend:latest
  
  Update_code:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    
    - name: CD
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: 22
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd k8s-docker
          git pull origin master
          docker pull ghcr.io/hsienbro/frontend
          docker pull ghcr.io/hsienbro/backend
          docker-compose up -d
          docker-compose down



